application:
  port: 8000
  host: 127.0.0.1

database:
  url: postgres://postgres:password@localhost:5432/nya

security:
  token_secret: changemeinproduction
  # 2 days
  token_expire_interval: 172800
